### ISSUE TITLE
troubleshooting question

### ISSUE THREAD

**Issue by anvnate** [Raphael-Boichot/Mitsubishi-M64282FP-dashcam#2]
Hello, 

I've successfully put this build together, it will reliably boot and load the config but will not connect with the sensor. I have checked continuity between the sensor and board, and the sensor is getting power to the correct pin. Can't find any continuity breaks between the sensor or anywhere else on the board. I'm new to Arduino but fairly confident this is soldered correctly. The GBC cart was claimed to be tested/working.

Have tried flashing the UF a few times, formatting/reinstalling the config. I was unable to get the longer install through Arduino IDE to boot. 

Could the sensor be bad? Any ideas?

**Comment by Raphael-Boichot** [comment]
Hello and glad to hear you are interested by the project.

The PCB you got is working for sure as I made one and I know for sure somebody else having one working from the same gerber.
This said, if you are sure of your soldering work, you can try to just change the ribbon cable with another one. The ones sold on aliexpress are crap and get easily broken at the first bending.

If you can send here images of the PCB near the sensor connection and a global image, I can try to see if there is any obvious 
issue. Any images of the connections from the sensor PCB to the DashBoy PCB would help.

Is the sensor working with a GB camera ? 

Raphaël

**Comment by Raphael-Boichot** [comment]
Oh, and can you send an image of the screen at boot also ?

**Comment by Raphael-Boichot** [comment]
Hello.

Apart from a possible defective sensor (which is very very unlucky but why not), I find your solder joints a bit on the "dry side". I would give a good reflow with more solder to all pins, both faces, with a bit a flux if you have some.

You are probably using a lead free solder which is great for environmental issues, but it requires a quite hot soldering iron, so I would also increase a bit the iron temperature to reflow (at least 300°C).

I would particularly insist on reflowing the level shifter area :

![image](https://github.com/Raphael-Boichot/Mitsubishi-M64282FP-dashcam/assets/63796796/eb2e1621-e4f5-4834-be61-d8ce853181ca)

My opinion: reflow this area and it will work.

Raphaël

**Comment by Raphael-Boichot** [comment]
![image](https://github.com/Raphael-Boichot/Mitsubishi-M64282FP-dashcam/assets/63796796/1288a409-14e5-498f-9786-d603da87cc5a)

These pins also need a good reflow

**Comment by anvnate** [comment]
I ended up pulling a few pieces off and could see where the solder hadn't flowed right. So, working on this again a bit more carefully with a better soldering set up and will update. Thank you for the help! I'll get this going.

**Comment by anvnate** [comment]
Hi Raphael,

I've tried to build the dash cam 5 times, I got 5 PCBs - reflow, retry, try
new parts, and I just can't get it to work. My solder joints are much
better, but either pins on the buck boost converter start to smoke, one of
the pins on the level shifter, or the pi... I got a hotter solder iron and
the joints look so much better than that first attempt, but that was the
closest I could ever get it to working. With the past few attempts I can't
the pi to show up to flash the bios.

Everything is affordable and I could keep trying, maybe start on a
breadboard to get a better idea of the circuit... I just don't really have
time to troubleshoot each connection or learn more about arduino just for
this project. I like the camera set up and I'm interested in using it for
some of my work, so I'm wondering if this is something you would be
interested in just selling directly? My intention would be to build an
enclosure and hook it up to CS lens mount from there.

Let me know.

Best,
Nate Ely
www.nathanely.com
@npely <https://www.instagram.com/npely/>

**Comment by Raphael-Boichot** [comment]
Hello.

The design is working for sure with the provided gerbers and components, I made some.
Can you send pictures of the "most working" design you have in good definition ?

Raphaël

**Comment by Raphael-Boichot** [comment]
Maybe a solution could be: send me your 5 defective boards and I will tinker a working one from them. The recycled parts should cover my shipping expenses for sending one back to you. I like repairing and recycling stuff.

Contact me on gmail (see my profile) if the deal is OK for you.

Raphaël

**Comment by anvnate** [comment]
That's very generous. I'll reach out via gmail shortly. I'm certain it's an
issue on my end and not with the design, likely something stupid I'm
missing in the build or a skill issue with soldering. I have a bunch of
parts from my various attempts I can include.

I appreciate the help troubleshooting to this point! I wish I had more time
to tinker with it myself and get it going, I'll be interested to know what
I screwed up.

**Comment by Raphael-Boichot** [comment]
Gmail is perfect for exchanging now.

**Comment by Raphael-Boichot** [comment]
You can follow the repair in discussion section now.
