### ISSUE TITLE
[suggestion] SD card formatting: diskpart on windows

### ISSUE THREAD

**Issue by 2ndmax** [Raphael-Boichot/Mitsubishi-M64282FP-dashcam#3]
Hello

Firstly, thank you for your work. I built the Dashboy Camera - and it works just fine. :-)

Secondly, I would like to share one thing, that might be useful for someone else. If you think so, you could include it in the description or trouble shooting section. Here it comes:

I built the Dashboy Camera but could not get the SD card working. Putting multiple different SD cards (mostly MicroSD cards, some 16, some 32 or 64 GB in size) in the SD card slot did not make any difference for me. First, I thought it might be an issue with SDXC vs. SDHC cards, thinking the reader could not read SDXC, even with less than 32 GB.

Now I come to believe it was the formatting all along, that somehow did not work. Up to this point I used the right click windows menu to format the SD cards in FAT32. Changing to the command line tool diskpart on windows however did the trick for me. After the "clean" command I could create a primary partition (up to 32 GB, not bigger for FAT32) on the SD card, which diskpart could format in FAT32. This formatted SD card is recognized and works.

I wanted to share this, because I was at a point, where I had no more ideas how to solve my SD card problem.

So again, thank you!

**Comment by Raphael-Boichot** [comment]
Hello.

I've added your tip in the troubleshooting section, thanks for it !

Enjoy the device ^^

Raphaël
